### ISSUE TITLE
Consider using arsenal::formulize

### ISSUE THREAD

**Issue by eheinzen** [rstudio-education/rmd4medicine#4]
`arsenal` author here.  A colleague showed me your presentation repo here, and I noticed that you use the motifs `rhs <- paste(..., collapse = "+")` and `as.formula(paste('arm ~', rhs))` a few times.  Since you've already got arsenal loaded, you could consider using `arsenal::formulize()`

**Comment by apreshill** [comment]
Thank you! That is interesting, although I'm not sure I know where you are talking about- I haven't released the workshop materials yet (nor written the `arsenal` part)! I'll look into the prep folders and see and be sure to use `formulize` when I get there.

**Comment by eheinzen** [comment]
Oh whoops: I meant to include the file path: `prep/tableone_arsenal.Rmd`

**Comment by apreshill** [comment]
I just found there as well, thank you- those were provided as prep help by my collaborator and haven't been integrated yet. When I do, would you be willing to look over if I tag you here to make sure I'm using `arsenal` best practices?

**Comment by eheinzen** [comment]
Got it--makes sense!  And absolutely, I'd be more than happy to!

**Comment by higgi13425** [comment]
Thanks, Ethan!Always helps to get arsenal advice from the source!
Peter
    On Friday, August 30, 2019, 09:36:03 AM EDT, Ethan Heinzen <notifications@github.com> wrote:  
 
 
Got it--makes sense! And absolutely, I'd be more than happy to!
